apiVersion: v1
kind: Service
metadata:
  name: team-michael-sousa
  # annotations:
  #   argocd.argoproj.io/sync-wave: "5"
spec:
  selector:
    app: team-michael-sousa
  # type: LoadBalancer | ClusterIP | NodePort
  ports:
    - name: http
      port: 3000 # service port
      protocol: TCP
      targetPort: 3000 # container port
